# Generated by Django 3.0.5 on 2020-04-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20200407_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
